//! Dhall rendering for den.dhall expressions.
//!
//! Port of the `render_den_dhall` function and its helpers in
//! `src/den_cli/core.py`. These are pure string transformations — no
//! I/O, no dhall parsing library, just template rendering.

use crate::project::{Backend, InferredDenSetup};
use std::path::Path;

pub fn render_den_dhall(config: &InferredDenSetup, dhall_dir: &Path) -> String {
    let backend_expr = match config.backend {
        Backend::Nix => "Types.Backend.Nix",
        Backend::Guix => "Types.Backend.Guix",
    };
    let dockerfile_expr = optional_text(config.dockerfile.as_deref());
    let nix_expr = if config.backend == Backend::Nix {
        render_nix_config(&config.nix_packages)
    } else {
        "None Types.NixConfig".to_string()
    };
    let guix_expr = if config.backend == Backend::Guix {
        render_guix_config(&config.guix_packages)
    } else {
        "None Types.GuixConfig".to_string()
    };
    let env_expr = render_env_list(&config.environment);
    let reasons = config
        .reasons
        .iter()
        .map(|r| format!("-- - {r}"))
        .collect::<Vec<_>>()
        .join("\n");

    let types_path = dhall_dir.join("Types.dhall");
    let defaults_path = dhall_dir.join("default.dhall");

    format!(
        "-- Generated by den setup\n\
         -- Inference reasons:\n\
         {reasons}\n\
         \n\
         let Types = {types_path}\n\
         \n\
         let Defaults = {defaults_path}\n\
         \n\
         in  {{ name = \"{name}\"\n\
         , backend = {backend_expr}\n\
         , dockerfile = {dockerfile_expr}\n\
         , restartPolicy = Some Types.RestartPolicy.Always\n\
         , healthcheck = None Types.Healthcheck\n\
         , ports = Defaults.defaultPorts\n\
         , volumes = Defaults.defaultVolumes\n\
         , resources = None Types.Resource\n\
         , secrets =\n\
             [ Types.Secret.FromEnv\n\
                 {{ name = \"TAILSCALE_AUTHKEY\", envVar = \"TAILSCALE_AUTHKEY\" }}\n\
             ]\n\
         , guix = {guix_expr}\n\
         , nix = {nix_expr}\n\
         , environment = {env_expr}\n\
         , domains = [] : List Text\n\
         }}",
        name = config.name,
        types_path = types_path.display(),
        defaults_path = defaults_path.display(),
    )
}

fn optional_text(value: Option<&str>) -> String {
    match value {
        None => "None Text".to_string(),
        Some(v) => format!("Some \"{v}\""),
    }
}

fn render_package_list(packages: &[String]) -> String {
    if packages.is_empty() {
        return "[] : List Types.Package".to_string();
    }
    let rows: Vec<String> = packages
        .iter()
        .map(|p| format!("{{ name = \"{p}\", version = None Text }}"))
        .collect();
    format!("[ {} ]", rows.join("\n        , "))
}

fn render_nix_config(packages: &[String]) -> String {
    format!(
        "Some\n      {{ packages = {}\n      , extraConfig = None Text\n      }}",
        render_package_list(packages)
    )
}

fn render_guix_config(packages: &[String]) -> String {
    format!(
        "Some\n      {{ channels = None (List Types.Channel)\n\
         , packages = {}\n\
         , services = None (List Text)\n      }}",
        render_package_list(packages)
    )
}

fn render_env_list(environment: &[(String, String)]) -> String {
    if environment.is_empty() {
        return "[] : List { mapKey : Text, mapValue : Text }".to_string();
    }
    let rows: Vec<String> = environment
        .iter()
        .map(|(k, v)| format!("{{ mapKey = \"{k}\", mapValue = \"{v}\" }}"))
        .collect();
    format!("[ {} ]", rows.join("\n        , "))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn optional_text_none() {
        assert_eq!(optional_text(None), "None Text");
    }

    #[test]
    fn optional_text_some() {
        assert_eq!(optional_text(Some("Dockerfile")), "Some \"Dockerfile\"");
    }

    #[test]
    fn render_package_list_empty() {
        assert_eq!(render_package_list(&[]), "[] : List Types.Package");
    }

    #[test]
    fn render_package_list_nonempty() {
        let pkgs = vec!["fish".to_string(), "git".to_string()];
        let result = render_package_list(&pkgs);
        assert!(result.starts_with("[ "));
        assert!(result.contains("fish"));
        assert!(result.contains("git"));
        assert!(result.ends_with(" ]"));
    }

    #[test]
    fn render_env_list_empty() {
        assert_eq!(
            render_env_list(&[]),
            "[] : List { mapKey : Text, mapValue : Text }"
        );
    }

    #[test]
    fn render_env_list_nonempty() {
        let env = vec![
            ("DEN_NAME".to_string(), "den-foo".to_string()),
            ("DEN_BACKEND".to_string(), "nix".to_string()),
        ];
        let result = render_env_list(&env);
        assert!(result.contains("DEN_NAME"));
        assert!(result.contains("den-foo"));
        assert!(result.contains("DEN_BACKEND"));
    }

    #[test]
    fn render_den_dhall_nix_backend() {
        let config = InferredDenSetup {
            name: "test-den".to_string(),
            backend: Backend::Nix,
            dockerfile: None,
            nix_packages: vec!["fish".to_string(), "git".to_string()],
            guix_packages: vec![],
            environment: vec![("DEN_NAME".to_string(), "den-test-den".to_string())],
            reasons: vec!["package.json detected".to_string()],
        };
        let dhall_dir = Path::new("/tmp/dhall");
        let result = render_den_dhall(&config, dhall_dir);
        assert!(result.contains("Types.Backend.Nix"));
        assert!(result.contains("test-den"));
        assert!(result.contains("None Text")); // dockerfile
        assert!(result.contains("None Types.GuixConfig"));
        assert!(result.contains("Some")); // nix config
        assert!(result.contains("package.json detected"));
        assert!(result.contains("Types.dhall"));
        assert!(result.contains("default.dhall"));
    }

    #[test]
    fn render_den_dhall_guix_backend_with_dockerfile() {
        let config = InferredDenSetup {
            name: "py-project".to_string(),
            backend: Backend::Guix,
            dockerfile: Some("Dockerfile".to_string()),
            nix_packages: vec![],
            guix_packages: vec!["python".to_string()],
            environment: vec![
                ("DEN_NAME".to_string(), "den-py-project".to_string()),
                ("DEN_BACKEND".to_string(), "guix".to_string()),
                ("DEN_DOCKERFILE".to_string(), "Dockerfile".to_string()),
            ],
            reasons: vec!["standalone Python project detected".to_string()],
        };
        let dhall_dir = Path::new("/tmp/dhall");
        let result = render_den_dhall(&config, dhall_dir);
        assert!(result.contains("Types.Backend.Guix"));
        assert!(result.contains("Some \"Dockerfile\""));
        assert!(result.contains("None Types.NixConfig"));
        assert!(result.contains("python"));
    }
}
